
language: objective-c
os: osx
sudo: required
matrix:
  include:
    - osx_image: xcode7.0
    - osx_image: xcode7.1
    - osx_image: xcode7.2b1

script:
  - ./setup.sh

notifications:
  email: true

branches:
  only:
    - master
