
language: objective-c
os: osx
sudo: required
matrix:
  include:
    - osx_image: xcode7.0
    - osx_image: xcode8
    - osx_image: xcode8.1

script:
  - TESTING=true ./bootstrap.sh
  - TESTING=true ./setup.sh

notifications:
  email: true

branches:
  only:
    - master
