
language: objective-c
os:
  - osx
sudo: required

osx_image:
  - xcode8.1
env:
  - BREW_SET=brew_set_1
  - BREW_SET=brew_set_2
  - BREW_SET=brew_set_3
  - BREW_SET=cask CASK_CMD_PCH=cask
matrix:
    include:
        - osx_image: xcode8
        - osx_image: xcode7.3
script:
  - TESTING=true ./bootstrap.sh
  - TESTING=true ./setup.sh

notifications:
  email: true

branches:
  only:
    - master
